name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']  # List Python versions
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        choco install ffmpeg

    - name: Run pytest
      shell: powershell
      run: |
        pytest

    - name: Run pre-commit hooks
      shell: powershell
      run: |
        pip install pre-commit
        pre-commit run --all-files

    - name: Install
      shell: powershell
      run: |
        pip install .
